import { useRef, useState } from 'react';
import { Icon } from '../employee/EmployeeScreen';
import { createInvitation, invitePath, inviteRoles, inviteStatus, inviteStatuses, updateInvitation, useInvitations, type InviteRole, type InviteStatus, type Team } from '../auth/invitations';
import { useTimedNotice } from '../../shared/useTimedNotice';
import './admin-invitations.css';

const date = (at: number) => new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }).format(at);
export default function AdminInvitations({ team, memberEmails, now, query, onBack }: { team: Team; memberEmails: string[]; now: number; query: string; onBack: () => void }) {
  const { invites } = useInvitations();
  const [email, setEmail] = useState('');
  const [role, setRole] = useState<InviteRole>('employee');
  const [filter, setFilter] = useState<'all' | InviteStatus>('all');
  const [error, setError] = useState('');
  const [linkToken, setLinkToken] = useState('');
  const [cancelToken, setCancelToken] = useState('');
  const [notice, showNotice] = useTimedNotice();
  const linkInput = useRef<HTMLInputElement>(null);
  const all = invites.filter(invite => invite.teamId === team.id);
  const visible = all.filter(invite => (filter === 'all' || inviteStatus(invite, now) === filter) && invite.email.includes(query.trim().toLowerCase()));
  const selected = all.find(invite => invite.token === linkToken);
  async function copy(token: string) {
    setLinkToken(token);
    try { await navigator.clipboard.writeText(`${window.location.origin}${invitePath(token)}`); showNotice('Ссылка скопирована. Можно отправить её коллеге.'); }
    catch { showNotice('Выдели ссылку ниже и скопируй вручную.'); window.setTimeout(() => { linkInput.current?.focus(); linkInput.current?.select(); }, 0); }
  }
  return <section className="admin-invitations" aria-label="Приглашения команды">
    <div className="invites-toolbar"><button className="admin-text-button" type="button" onClick={onBack}>← Сотрудники</button><span>КОМАНДА / <strong>{team.name || 'Моя команда'}</strong></span></div>
    <div className="invites-layout"><div className="invites-main">
      <div className="invites-filters" aria-label="Статусы приглашений">{(['all', 'pending', 'accepted', 'expired', 'revoked'] as const).map(status => <button type="button" key={status} aria-pressed={filter === status} onClick={() => setFilter(status)}><span>{status === 'all' ? 'Все' : inviteStatuses[status]}</span><strong>{status === 'all' ? all.length : all.filter(invite => inviteStatus(invite, now) === status).length}</strong></button>)}</div>
      <section className="admin-panel invites-list" aria-labelledby="invites-list-title"><div className="admin-panel__heading"><div><h2 id="invites-list-title">Приглашения</h2><p>Персональная ссылка · 7 дней · одно вступление</p></div><span>{visible.length} из {all.length}</span></div>
        {visible.length ? visible.map(invite => { const status = inviteStatus(invite, now); return <article className="invite-row" key={invite.token}><div className="invite-row__identity"><span className={`invite-avatar invite-avatar--${invite.role}`}><Icon name={invite.role === 'admin' ? 'bolt' : 'team'} /></span><div><strong>{invite.email}</strong><span>{inviteRoles[invite.role]}{invite.acceptedName ? ` · ${invite.acceptedName}` : ''}</span></div><span className={`invite-status invite-status--${status}`}>{inviteStatuses[status]}</span></div><div className="invite-row__bottom"><span>{status === 'pending' ? 'Действует до' : status === 'expired' ? 'Истекло' : 'Создано'} {date(status === 'pending' || status === 'expired' ? invite.expiresAt : invite.createdAt)}</span><div className="invite-row__actions">{status === 'pending' && <><button type="button" onClick={() => copy(invite.token)} aria-label={`Скопировать ссылку для ${invite.email}`}>Скопировать</button><a href={invitePath(invite.token)} target="_blank" rel="noreferrer" aria-label={`Открыть приглашение для ${invite.email}`}>Открыть ↗</a><button type="button" className="invite-cancel" aria-label={`Отменить приглашение для ${invite.email}`} onClick={() => setCancelToken(invite.token)}>Отменить</button></>}{(status === 'expired' || status === 'revoked') && <button type="button" onClick={() => { setEmail(invite.email); setRole(invite.role); setError(''); document.getElementById('invitation-email')?.focus(); }}>Пригласить снова →</button>}</div></div>{cancelToken === invite.token && status === 'pending' && <div className="invite-confirm" role="group" aria-label={`Подтвердить отмену для ${invite.email}`}><p>Отменить приглашение? Эта ссылка перестанет работать.</p><button type="button" onClick={() => { try { updateInvitation(invite.token, 'revoke'); setCancelToken(''); showNotice('Приглашение отменено. Ссылка больше не действует.'); } catch (reason) { showNotice(reason instanceof Error ? reason.message : 'Не удалось отменить приглашение.'); } }}>Да, отменить</button><button type="button" onClick={() => setCancelToken('')}>Оставить</button></div>}</article>; }) : <div className="employee-empty"><Icon name="team" /><h3>{all.length ? 'Таких приглашений нет' : 'Команда начинается с приглашения'}</h3><p>{all.length ? 'Измени статус или поисковый запрос.' : 'Создай первую ссылку и отправь её коллеге.'}</p></div>}
      </section>
    </div><aside className="admin-panel invites-create" aria-labelledby="invite-create-title"><div className="admin-panel__heading"><div><p className="invites-kicker">ДОБАВИТЬ В КОМАНДУ</p><h2 id="invite-create-title">Новое приглашение</h2></div><Icon name="plus" /></div><form onSubmit={event => { event.preventDefault(); try { const invite = createInvitation(team.id, email, role, memberEmails); setLinkToken(invite.token); setEmail(''); setError(''); setFilter('all'); showNotice('Ссылка создана. Скопируй её и отправь коллеге.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось создать ссылку.'); } }}><label htmlFor="invitation-email">Почта коллеги</label><input id="invitation-email" type="email" value={email} maxLength={254} required autoComplete="off" placeholder="name@example.com" onChange={event => { setEmail(event.target.value); setError(''); }} /><label htmlFor="invitation-role">Роль в команде</label><select id="invitation-role" value={role} onChange={event => setRole(event.target.value as InviteRole)}><option value="employee">Сотрудник</option><option value="admin">Администратор</option></select><p className="invites-role-hint">{role === 'admin' ? 'Сможет управлять командой, задачами и приглашениями. Личные заметки других администраторов ему недоступны.' : 'Увидит свои задачи, общий GOAT и личный рейтинг.'}</p>{error && <p className="admin-task-editor__error" role="alert">{error}</p>}<button type="submit" className="employee-button employee-button--primary"><Icon name="plus" />Создать ссылку</button><p className="invites-form-foot">Приглашённый войдёт или создаст аккаунт с указанной почтой. Роль уже выбрана тобой.</p></form>
      {selected && inviteStatus(selected, now) === 'pending' && <div className="invite-share" role="region" aria-label="Ссылка приглашения"><strong>Ссылка готова</strong><p>Для {selected.email}</p><input ref={linkInput} aria-label="Ссылка приглашения" readOnly value={`${window.location.origin}${invitePath(selected.token)}`} onFocus={event => event.target.select()} /><button className="employee-button" type="button" onClick={() => copy(selected.token)}>Скопировать ссылку</button><a href={invitePath(selected.token)} target="_blank" rel="noreferrer">Посмотреть приглашение ↗</a></div>}
    </aside></div>
    {notice && <div className="employee-toast" role="status"><Icon name="check" /><p>{notice}</p><button className="employee-icon-button" type="button" aria-label="Закрыть уведомление" onClick={() => showNotice('')}><Icon name="close" /></button></div>}
  </section>;
}
